// Regenerates src/vendor/leaflet.ts from the installed leaflet package, so the
// RouteMap WebView can inline Leaflet instead of fetching it from a CDN.
// Run after changing the leaflet version: npm run vendor:leaflet
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const dist = dirname(require.resolve('leaflet/dist/leaflet.js'));
const { version } = require('leaflet/package.json');
const js = readFileSync(join(dist, 'leaflet.js'), 'utf8');
const css = readFileSync(join(dist, 'leaflet.css'), 'utf8');

// Both are inlined into <script>/<style> tags; a closing tag would end them early.
if (/<\/script/i.test(js) || /<\/style/i.test(css)) {
  throw new Error('Leaflet source contains a closing tag and cannot be inlined as-is');
}

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'vendor', 'leaflet.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/vendor-leaflet.mjs from leaflet@${version} — do not edit.\n` +
    `// Leaflet is BSD-2-Clause licensed; its license header is kept in LEAFLET_JS.\n` +
    `export const LEAFLET_VERSION = ${JSON.stringify(version)};\n` +
    `export const LEAFLET_CSS = ${JSON.stringify(css)};\n` +
    `export const LEAFLET_JS = ${JSON.stringify(js)};\n`,
);
console.log(`Wrote ${out} (leaflet@${version})`);
